### ISSUE TITLE
One is missing from UUID default alphabet

### ISSUE THREAD

**Issue by Nigel2392** [skorokithakis/shortuuid#100]
I am not sure if this is an issue, or is intentional.

The one seems to be missing from the alphabet in the ShortUUID class.

23456789 -> 123456789

Same thing for some other letters, the "I" and "O" are missing from the capitalized alphabet, and the "L" was missing from the uncapitalized alphabet.
```
alphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ" "abcdefghijkmnopqrstuvwxyz"
```
Should probably be: `alphabet = "123456789" "ABCDEFGHIJKLMNOPQRSTUVWXYZ" "abcdefghijklmnopqrstuvwxyz"`

If this was intentional, why if I may ask?

**Comment by skorokithakis** [comment]
Yes, this is because 1, l, and I look too much alike.
