### ISSUE TITLE
please tag releases and include release notes

### ISSUE THREAD

**Issue by jab** [skorokithakis/shortuuid#26]
Just noticed there was a new release of shortuuid. Looked for a CHANGELOG under https://pypi.python.org/pypi/shortuuid and https://github.com/stochastic-technologies/shortuuid/ but didn't find one. Went to https://github.com/stochastic-technologies/shortuuid/releases in hopes of seeing this info there, but came up empty since you're not tagging releases. Would you consider tagging releases and adding release notes? In the meantime, users have to comb through e.g. https://github.com/stochastic-technologies/shortuuid/commits/develop to try to tease out what's changed when there's a new release.

Thanks for the great work on shortuuid.

**Comment by jab** [comment]
Here is an example of maintaining release notes alongside each release: https://github.com/jab/bidict/releases

GitHub makes this a really nice user experience :)

**Comment by skorokithakis** [comment]
That would be great, do you know of a good way to do that? How does the Github integration work, do you know?

**Comment by jab** [comment]
Great there's interest! Check out https://github.com/blog/1547-release-your-software for a walkthrough.

In general GitHub is great about publishing documentation of their features on their blog and at https://help.github.com if you're ever looking for how to do something.

**Comment by skorokithakis** [comment]
I've started using `semantic-release` so this can be closed, thank you.
