### ISSUE TITLE
Failing tests checking length of shortuuid

### ISSUE THREAD

**Issue by davecap** [skorokithakis/shortuuid#27]
I'm seeing some randomly failing tests on the following line:
https://github.com/stochastic-technologies/shortuuid/blob/master/shortuuid/tests.py#L41

That assert seems to fail <1% of the time. I'm not exactly sure why though. I'm seeing values that are < 116 in length (115, 116). What's the reason for that lower bound?

**Comment by skorokithakis** [comment]
I was guarding against leading zeros, which, if I recall correctly, would not appear in the output. It appears I was too optimistic, though. I'm not sure why the padding code does not work here, though.

**Comment by skorokithakis** [comment]
Closing this issue as it's a bit stale.
