### ISSUE TITLE
Namespace type check could be better

### ISSUE THREAD

**Issue by jace** [skorokithakis/shortuuid#32]
[ShortUUID determines namespace using the following code](https://github.com/skorokithakis/shortuuid/blob/e60207b36cb2e157e97fe35386d8ecc52e7450d7/shortuuid/main.py#L82):

```python
# If no name is given, generate a random UUID.
if name is None:
    uuid = _uu.uuid4()
elif "http" not in name.lower():
    uuid = _uu.uuid5(_uu.NAMESPACE_DNS, name)
else:
    uuid = _uu.uuid5(_uu.NAMESPACE_URL, name)
```

However, this should check for `http://` or `https://` at the _beginning_ of the string, not anywhere in the middle, as it'll currently consider `myhttpdomain.com` as a URL instead of a domain. The correct if condition is: `elif not name.lower().startswith(('http://', 'https://'))`

**Comment by skorokithakis** [comment]
You are, of course, correct. Good shout on the tuple for `startswith`, too, I had never noticed that. Thank you!
