### ISSUE TITLE
LSB-first encoding makes lexicographic ordering hard

### ISSUE THREAD

**Issue by letmaik** [skorokithakis/shortuuid#35]
Let's say I want to group a number of shortuuids into several non-overlapping partitions and use a string-based comparison that defines each partition, e.g. `"aaa" <= shortuuid < "bbb"`. Since shortuuids are LSB-first, this isn't possible, since 0 corresponds to '2222222222222222222222' and 1 corresponds to '3222222222222222222222'. With UUIDs generated with `str(uuid.uuid4())` this would be '00000000-0000-0000-0000-000000000000' for 0 and '00000000-0000-0000-0000-000000000001' for 1, which is useable for lexicographic ordering based on their integer representation.
Is there a specific reason why shortuuids are LSB-first? In my case it complicates things, but are there advantages I'm ignoring?

**Comment by skorokithakis** [comment]
No, and I agree that this property should be preserved. If you want to submit a PR, I'll happily merge it, since we currently make no guarantees about the endianness of the UUID. Hopefully nobody is relying on that, but we can start guaranteeing that they're MSB-first.

**Comment by letmaik** [comment]
LSB-first is indirectly guaranteed. If someone has stored a shortuuid somewhere and wants to go to a normal uuid (maybe to bridge two systems), then they would use `shortuuid.decode(..)`. And this translation would suddenly break if MSB-first is used. I see two options: 1) Break it and offer LSB-first as an option for backwards-compatibility (in case anyone needs it), or 2) Don't break it and offer MSB-first as an option (off by default). Since the version numbers of shortuuid are still 0.x it would be ok to break things and just increase the minor version (assuming the library follows semantic versioning).

**Comment by skorokithakis** [comment]
> LSB-first is indirectly guaranteed.

It is, but indirect guarantees should not be relied upon.

> And this translation would suddenly break if MSB-first is used.

This is the more important consideration, in my opinion.

The library *does* follow semantic versioning, so I am inclined to break backwards compatibility and make MSB the default, because that's the default operation in UUIDs. I think it would be wise to include a method called `convert_shortuuid` for one or two minor versions, just so people can easily convert their LSB UUIDs to MSB.

I'm generally very averse to breaking backwards compatibility, but I don't think many people use this guarantee, or encode/decode short UUIDs. I might be greatly mistaken, I've just never used the decoding functionality or seen someone here use it.

**Comment by keanemind** [comment]
In my pull request, I have changed both `encode()` and `decode()`, so any existing code that relies upon stored shortuuids decoding to certain uuids will break. However, I am not sure a `convert_shortuuid` method is necessary. Can't users just use `a_short_uuid[::-1]` to convert?

**Comment by letmaik** [comment]
@keanemind I agree, since the difference between LSB/MSB is just the reversal of the string, it is simple enough and doesn't require an additional function. I gave your PR a quick try and it worked as expected for me.

**Comment by skorokithakis** [comment]
The functions are for documentation and user ease of use, it's not because it's hard to reverse a string. I agree that we could go without, but it doesn't hurt to include them for a release or two. I'll review ASAP, thank you!

**Comment by skorokithakis** [comment]
Another way to go is to just make `string_to_int` accept a second parameter, called `msb=True` so people can set it to `False` if they have an old-style string.

**Comment by keanemind** [comment]
Agreed, feel free to add to the PR. I guess the most important thing is documentation.

**Comment by skorokithakis** [comment]
Will do, thank you. The documentation is, indeed, very important, I'll have to write it up before I merge this.

**Comment by skorokithakis** [comment]
This has been merged, thank you all for your help. @letmaik, could you test the current `master` HEAD and let me know if everything looks good (hopefully including `decode(uuid, legacy=True)`?

Thanks again!

**Comment by letmaik** [comment]
Did a quick test incl. legacy, looks good to me!

**Comment by skorokithakis** [comment]
Great, thank you!

**Comment by vlanse** [comment]
You guys just broken backward compatibility for anyone who used version <=0.5.0.
At least you could keep previous interface to work as it was for people who was not concerned with LSB/MSB problem.

**Comment by skorokithakis** [comment]
@vlanse what did this change break for you?

**Comment by vlanse** [comment]
```
>> shortuuid.__version__
'0.5.0'

>> shortuuid.encode(uuid.UUID('b1d97ac6-dcf7-4567-aa13-245e9b2f8a77'))
'mJTdQRy49Z6v4RcaFvifeZ'
```

```
>> shortuuid.__version__
'0.5.1'

>> shortuuid.encode(uuid.UUID('b1d97ac6-dcf7-4567-aa13-245e9b2f8a77'))
'ZefivFacR4v6Z94yRQdTJm'

>> shortuuid.decode('mJTdQRy49Z6v4RcaFvifeZ')
UUID('f34d582b-bcbc-edd9-d688-38439ee034ff')
```

You could keep old interface working with LSB-first encoding at least...

**Comment by skorokithakis** [comment]
I thought we included a parameter to use the legacy decoding mode, but it looks like we didn't. I'll release a new version now with it, sorry.

**Comment by vlanse** [comment]
More important, legacy mode should be used by default

**Comment by skorokithakis** [comment]
That's going to be an issue, since legacy mode is basically "wrong" (it inverts the bytes). Breaking backwards compatibility is an issue too, but I don't want to break it twice in two releases...

I wonder if there's a way to detect which version a uuid uses, but I don't think so...

**Comment by vlanse** [comment]
Looks like there is no such way to detect encoding used
Btw, you released 0.5.1 several hours ago, so I think no one had already used in production. In opposite to "wrong" version...

**Comment by skorokithakis** [comment]
Oh damn, is it in this version? I thought we released this functionality a while ago. I will revert asap, thanks.

**Comment by skorokithakis** [comment]
Alright, so this version encodes UUIDs with the MSB first, which means that if `legacy=True` by default, it won't be able to decode its own UUIDs. I will revert this and release 0.5.2, then release 1.0.0 with the MSB stuff built-in.

0.5.1 should have been 1.0.0, but the changelog wasn't correct and confused me...

**Comment by skorokithakis** [comment]
Alright, 1.0.0 has been released.
