### ISSUE TITLE
Usage of pep8 is deprecated

### ISSUE THREAD

**Issue by scarabeusiv** [skorokithakis/shortuuid#38]
Hello the project uses pep8 in tests to do some formatting checks, yet by upstream pep is now deprecated (well renamed) in favor of https://github.com/PyCQA/pycodestyle.

Could you please migrate the code to use the pycodestyle instead?

**Comment by skorokithakis** [comment]
Hmm, we use pre-commit for the actual style checking, it's just that we have a PEP8 test. Is something breaking for you? What is the advantage of the project migrating to pycodestyle?

**Comment by scarabeusiv** [comment]
We just run setup.py test in openSUSE and we dropped pep8 from distribution in favor of pycodestyle. Suddenly this package was not able to pass the tests. The commit above of course solves the issue for us :)

**Comment by skorokithakis** [comment]
Ah I see. Unfortunately now Travis CI is having problems, but I guess I can just only run those tests on 3.6.
