### ISSUE TITLE
ValueError: int is out of range (need a 128-bit value)

### ISSUE THREAD

**Issue by Skyross** [skorokithakis/shortuuid#41]
Hello!

Thank you for this package. Need some pieces of advice about decoding. I've found some shortuuids that raises:
```
...
    return _uu.UUID(int=string_to_int(string, self._alphabet))
  File "/usr/lib/python3.6/uuid.py", line 174, in __init__
    raise ValueError('int is out of range (need a 128-bit value)')
ValueError: int is out of range (need a 128-bit value)
```
The code:
```python
from shortuuid import decode
decode('pyKuFXRZEDMv4Zng4RgtBz')
```

Checked on:
- Python: 3.6
- shortuuid: 0.5.0 and master

Thank you in advance!

**Comment by skorokithakis** [comment]
Hello, can you also post the code that encodes this UUID?

**Comment by Skyross** [comment]
We are using `ShortUUIDField` (from `django-shortuuidfield==0.1.3`) and that shortuuid was generated as defaults values. Looks like this code is responsible for that:
```python
def pre_save(self, model_instance, add):
    """
    This is used to ensure that we auto-set values if required.
    See CharField.pre_save
    """
    value = super(ShortUUIDField, self).pre_save(model_instance, add)
    if self.auto and not value:
        # Assign a new value for this attribute if required.
        value = six.text_type(shortuuid.uuid())
        setattr(model_instance, self.attname, value)
    return value
```

**Comment by Skyross** [comment]
Looks like I've found some code that overrides that value in a custom way without usage of `shortuuid.uuid()` call! Sorry for bothering, closing this!

**Comment by skorokithakis** [comment]
No problem!
