### ISSUE TITLE
Add simple command-line interface

### ISSUE THREAD

**Issue by merwok** [skorokithakis/shortuuid#42]
Hello!  Thanks for this lib, it’s really useful to generate unique IDs painlessly.

Often I want to generate a bunch of values, for example to define object IDs in test fixtures.  It’s easy enough to open a Python shell to do that, but would be even easier with a command-line interface :slightly_smiling_face: 

Simplest version:

```python
# add shortuuid/__main__.py
from .main import uuid

if __name__ == "__main__":
    print(uuid())
```

```
$ python -m shortuuid
QG6wVwX8X4kqy829JE9zLT
```

Featureful version: add params to control length [*] and number of IDs to generate.

*: I’m not sure if this should use ShortUUID.random or uuid+truncate

**Comment by skorokithakis** [comment]
Hmm, that's a good idea. I would not be opposed to it, would you care to open a PR?

**Comment by merwok** [comment]
Yes!  Simple or full version?

**Comment by skorokithakis** [comment]
Probably the simple version first, and we can take it from there!
