### ISSUE TITLE
Edge case when serializing UUID(int=0) with pad_length=0

### ISSUE THREAD

**Issue by ivanistheone** [skorokithakis/shortuuid#48]
I'm using truncated `shortuuid` and encoding them with `pad_length=0` to avoid the leading 2s (first char of alphabet).

It's working great overall (roundtrip encoding and decoding), except for the edge case of encoding `uuid.UUID('00000000-0000-0000-0000-000000000000')` which ends up as empty string:

```
>>> shortuuid.encode( uuid.UUID('00000000-0000-0000-0000-000000000000'), pad_length=0)
''  # empty str
```
This is not a bug and technically correct output, however it causes some problems in practice since other code treats this as falsy, and cannot be displayed as a link text since nothing to click on.

Perhaps we should make an exception in this case and treat it as pad_lenght=1 to return `'2'` as the code?
This way we can get back to full round trip:
```
>>> shortuuid.decode('2')
UUID('00000000-0000-0000-0000-000000000000')
```

**Comment by ivanistheone** [comment]
On second thought, I looked at the code and there is no way to cater for this edge case other than manual check like 

    uuid == UUID('00000000-0000-0000-0000-000000000000')  ?

for each call to `encode` which doesn't seem warranted (extra compute just for one very rare edge case that happens only in tests).

Motion to close issue.

**Comment by skorokithakis** [comment]
I agree with the assessment, I think we should avoid this edge case and the layer above can test for this and add the "2" then.
