### ISSUE TITLE
Feature request: ShortUUIDField for Django models

### ISSUE THREAD

**Issue by ivanistheone** [skorokithakis/shortuuid#50]
It would be nice to have `ShortUUIDField` which is a subclass of Django's `UUIDField` that uses UUIDs internally, but show sortuuids to users.

I have some WIP code that implements this:
 - https://github.com/GROCCAD/groccad/blob/main/standards/fields.py

A usage example:
```
class Node(models.Model):
    id = ShortUUIDField(primary_key=True, prefix='N', length=7)
    ...

```
which will create shortcodes of length at most `7`, and each id will start with prefix `N`.

It was kind of tricky to add tests for this:
  - https://github.com/GROCCAD/groccad/blob/main/standards/tests/test_shortuuidfield.py
     (largely imitation of Django tests for UUIDField)
  - test make use the "test models" defined in [tests/models.py](https://github.com/GROCCAD/groccad/blob/main/standards/tests/models.py)
  - And there is a [helper function](https://github.com/GROCCAD/groccad/blob/main/standards/tests/__init__.py) that registers a "test-only app" that makes this work

I realize the defaults (truncation to length=7 and prefix) in the code samples might not be suitable for general use, so not going to open a PR yet. I'm going to keep using this for the specific application an possibly followup with a PR in January 2021 if you think this would be worth adding to this repo.

Opening this issue to keep the links together and so I'll remember to get back to this.

**Comment by skorokithakis** [comment]
This seems very worthwhile to me, thank you! To add tests you need to mostly mock a Django project, like you did, yeah.

I'll be eagerly expecting an update, thanks again.

**Comment by shukryzablah** [comment]
django-extensions has a ShortUUIDField https://github.com/django-extensions/django-extensions/blob/master/django_extensions/db/fields/__init__.py

**Comment by skorokithakis** [comment]
Thanks for that, @shukryzablah. Our licenses are compatible, I think we could upstream that.

**Comment by skorokithakis** [comment]
I've added this, thanks!

**Comment by ivanistheone** [comment]
Thanks for working on this!
https://github.com/skorokithakis/shortuuid#django-field It looks great!

**Comment by skorokithakis** [comment]
Thank you!
