### ISSUE TITLE
Unclear how to use UUID5, namespace

### ISSUE THREAD

**Issue by connerxyz** [skorokithakis/shortuuid#52]
My understanding of UUID v5 is you can provide a namespace _and_ a value to get a deterministic hash for that namespace + value.

I see you can provide `shortuuid.uuid` a `name` argument, and I see in the code how that maps to `uuid5` in the code... but it's unclear to me what to do from there.

I see that providing the same `name` argument produces the same output (as expected!).  How do you now combine a namespace and value to get a deterministic output, such that `func(namespace, value)` produces the same output every time (where `namespace` remains the same and `value` changes)?

Perhaps I'm misunderstanding something. Thanks.

**Comment by skorokithakis** [comment]
I don't think you're misunderstanding anything, it's just that UUID 5 was a bit of an afterthought. I don't think anyone else has used the UUID 5 features in the ten years of shortuuid's existence, and I haven't used it myself either. I added it as an "if you need this, I guess you'll know how to use it, because I don't". Maybe it doesn't make sense at all here, though.

**Comment by connerxyz** [comment]
Okay. Looks like I might be able to just append the namespace and string and provide that as `name`. Probably not "proper" with regard to the UUID v5 spec, but it might suit my purposes.

**Comment by skorokithakis** [comment]
What do you need to do exactly?

**Comment by connerxyz** [comment]
I want (1) the shortest possible UUID, (2) the least possible number of collisions – of course, and (3) to be able to independently produce the UUID given the same set of data (from 2 or 3 strings let's say).

**Comment by skorokithakis** [comment]
Hmm, 1 and 2 are mutual tradeoffs, the shorter the UUID the more the collisions. 3 should be doable.

**Comment by connerxyz** [comment]
Right. I was thinking something like...

```
shortuuid.uuid(name="mynamespace"+"var1"+"var2")
```

**Comment by skorokithakis** [comment]
That should work fine, if all you need is determinism, yep.
