### ISSUE TITLE
setup.py interprets python 3.10 as python 3.1

### ISSUE THREAD

**Issue by tirkarthi** [skorokithakis/shortuuid#53]
sys.version returns "3.10" and comparing it with "3.5" will take it as "3.1" and return false. Using sys.version_info is a better way to check for version. Fedora bug : https://bugzilla.redhat.com/show_bug.cgi?id=1900743

```
~/cpython/python
Python 3.10.0a5+ (heads/master:cd80f430da, Feb 17 2021, 14:08:19) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.10.0a5+ (heads/master:cd80f430da, Feb 17 2021, 14:08:19) \n[GCC 7.5.0]'
>>> sys.version >= "3.5"
False
```

https://github.com/skorokithakis/shortuuid/blob/62cc86c20f055c1618096f637ac3f62ed453be82/setup.py#L8

**Comment by skorokithakis** [comment]
Oops, thanks for this! Can you file a PR?

**Comment by tirkarthi** [comment]
Sure, created https://github.com/skorokithakis/shortuuid/pull/54
