### ISSUE TITLE
README not that complete

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [skorokithakis/shortuuid#55]
Hi,
I am trying to parse a url and short with `shortuuid` but i cant find anything in the README that explains how to do that.
I did `shortuuid.uuid(name="www.google.pt")` but how can i go to www.google.pt using the uuid that i get?

Thanks

**Comment by skorokithakis** [comment]
You can't, this is a namespaced UUID. I recommend reading up on version 5 UUIDs, but it sounds like that's not what you need.
