### ISSUE TITLE
Using this as default in SQLAlchemy Column generates duplicates

### ISSUE THREAD

**Issue by psqnt** [skorokithakis/shortuuid#56]
I have a flask project I am working on and noticed that I was consistently generating duplicates on both mac and linux when saving a record and using shortuuid.uuid() as the default value in the column:

For example:
```
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    post_code = db.Column(db.String(30), default=shortuuid.uuid())
```
I seemed to have solved the issue by forcing unique on the database level and then creating the shortuuid.uuid() explicitly when creating a model (instead of leaving it blank)
What I mean is this would generate duplicates:
```
p = Post()
db.session.add(p)
db.session.commit()
```
but this is not generating duplicates (so far)
```
code = shortuuid.uuid()
p = Post(post_code=code)
db.session.add(p)
db.session.commit()
```

Just curious if there is any information on this

**Comment by skorokithakis** [comment]
Remove the parentheses after `uuid` or you'll always get the same UUID due to eager evaluation.

**Comment by psqnt** [comment]
I woke up this morning to comment on this saying I made a mistake with the parentheses after reading the sqlalchemy documentation on defaults. You beat me to it! Thanks!
