### ISSUE TITLE
Release update version to handle building on Python 3.10

### ISSUE THREAD

**Issue by synapticarbors** [skorokithakis/shortuuid#58]
The current release of this package does not include the fixes to the `setup.py` that allow it to be built under python 3.10. It would be great if a new release could be pushed out make the change available on pypi.

**Comment by skorokithakis** [comment]
Ah yep, I'll do that, thanks! I wanted to include a Django UUID field but it doesn't look like that'll make it in time.

**Comment by skorokithakis** [comment]
I've released 1.0.2 with an extra file by mistake, because my manual packaging skills are rusty. Hopefully it won't affect anything.
