### ISSUE TITLE
Using pkg_resources makes package load really slow

### ISSUE THREAD

**Issue by chrisjsewell** [skorokithakis/shortuuid#59]
Heya, this change really hurts package loading times 😬 
https://github.com/skorokithakis/shortuuid/blob/bcd01ceaf2419d874b8543e6d7c28e2c56da7a91/shortuuid/__init__.py#L13

For example, with our CLI this change has meant an increase in load time from ~0.3 seconds to ~0.8 seconds!

`pkg_resources` is essentially deprecated, in part, for this very reason; replaced by https://docs.python.org/3/library/importlib.html#module-importlib.resources and the https://github.com/python/importlib_metadata backport

**Comment by skorokithakis** [comment]
Hey @chrisjsewell, thanks for this! I mixed up the old and new methods :( Can you check the latest master and see that it works properly?

**Comment by chrisjsewell** [comment]
also, the error to catch is `importlib_metadata.PackageNotFoundError`

**Comment by skorokithakis** [comment]
Hm, right. Given the frequency with which this library changes, I'm just going to type the version in by hand :P

**Comment by chrisjsewell** [comment]
Haha yep that's good by me!
(with setuptools or flit, you can just have the version read from the init and you don't have to put it in the pyproject.toml/setup.cfg)

**Comment by skorokithakis** [comment]
But I want it in the `pyproject.toml`, as it's easier for my deployment tooling to parse :/ Too bad, thanks for your help though!

**Comment by socketpair** [comment]
https://github.com/pypa/setuptools/issues/926
