### ISSUE TITLE
COPYING file no longer contained in source

### ISSUE THREAD

**Issue by astamminger** [skorokithakis/shortuuid#62]
Hi @skorokithakis 

Since v1.0.3 the COPYING file is no longer contained within the source. This currently fails the builds on conda-forge (conda-forge/shortuuid-feedstock#17). Would you mind creating a new release re-adding the COPYING file to the package source? Otherwise I would need to add and verify it manually on every release.

Thanks!

**Comment by skorokithakis** [comment]
Certainly, I think the move to Poetry messed something up. I'll see how to reinclude the file.

**Comment by skorokithakis** [comment]
Alright, that should be good (and 1.0.8 is released). Please let me know if this isn't fixed!
