### ISSUE TITLE
Some new IDs being generated using legacy mode

### ISSUE THREAD

**Issue by vizbird** [skorokithakis/shortuuid#66]
On shortuuid v1.0.8, I am running into an issue where sometimes generating a new random id results in a legacy mode uuid:

``` python
shortuuid.ShortUUID().random(length=22)
>>> 'sPQ3KBZLjzHhETzs3ufGCQ'

shortuuid.decode('sPQ3KBZLjzHhETzs3ufGCQ')
>>> ValueError: int is out of range (need a 128-bit value)

shortuuid.decode('sPQ3KBZLjzHhETzs3ufGCQ', legacy=True)
>>> UUID('7ca96621-cf86-aca5-f7d1-f07d4354140c')
```

The expected behavior is that any new shortuuid generated could be decoded and re-encoded without having to check for legacy mode: 

```python
id = shortuuid.ShortUUID().random(length=22)
id == shortuuid.encode(shortuuid.decode(id))
```

**Comment by skorokithakis** [comment]
Strings generated with `.random()` aren't UUIDs, they're just random strings, and thus encoding/decoding is not supported on them.
