### ISSUE TITLE
python3 -m shortuuid not working

### ISSUE THREAD

**Issue by LuKlimas** [skorokithakis/shortuuid#67]
Hello.
I was trying to use cli implementation of your package, but got this error.
`python3 -m shortuuid`
`/.venv/bin/python3: No module named shortuuid.__main__; 'shortuuid' is a package and cannot be directly executed`

shortuuid version: 1.0.8
python version: 3.8.6
os: macos

**Comment by skorokithakis** [comment]
Can you try running `shortuuid` directly?

**Comment by LuKlimas** [comment]
Directly running it works fine. Thank you. Just update the documentation to avoid questions like this in the future.

**Comment by skorokithakis** [comment]
Yep, didn't realize the README was out of date, thanks!
