### ISSUE TITLE
shortuuid performance and sorting

### ISSUE THREAD

**Issue by agentgt** [skorokithakis/shortuuid#69]
I was playing with our Java UUID shortner I wrote several years ago and I decided to see what other folks are doing and came across library.

Anyway I have few critiques. 

The algorithm as I understand  turns the UUID into one giant 128 bit integer and divmods appending the remainder to a string. The most significant part of the UUID is appended first but the contents of the most significant has the most significant right most. For example  base10 a "100" would be 001 or in base57 m3.

There are two problems to this approach:

 * Sorting is no longer the same. That is if you have a list of UUIDs and list of corresponding shortuuids the sort order will not be same.  This is because it follows the bit order which makes since for a generic encoding algorithm but I don't think its good for a UUID shortner. 
 * The algorithm is very slow on Java. Or at least this implementation which appears to be a clone of the golang https://github.com/hsingh/java-shortuuid and mostly follows the python version.

An easy replacement for the Java one is to use [Bitcoin's Base58 and just change the alphabet](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/Base58.java) which is originally what I used to use for UUID shortening. However Base58 divmods byte by byte and does not construct a full 128 bit integer.

Still Base58 is actually still not that fast compared to say Base64 and that is obviously because of power of 2 division.

My algorithm is almost as fast as base 64.
My algorithm works by divmoding longs (64 bit numbers in java) one at a time. This is fine because a UUID is two 64 bit numbers. Secondly there are tricks [divmoding 64 bit numbers super fast](https://github.com/PoslavskySV/libdivide4j/blob/master/src/main/java/cc/redberry/libdivide4j/FastDivision.java) even if they are not powers of 2 divisors.
Secondly it appends the most significant left to write to preserve lexicographical sort order. Padding is required but based on my tests only like ~2% of UUIDs have less than 22 characters (I was too lazy to do the math).

Anyway before I go set an opensource repository and try to port it to python I wanted to get some feedback. Is this a bad idea?

**Comment by skorokithakis** [comment]
Hmm, that sounds good, but keep in mind that this library doesn't just encode UUIDs, but also encodes random bytes into short IDs, so that needs to work with the encoder as well.

**Comment by agentgt** [comment]
It can encode random bytes its just not efficient on space if the bytes are not a multiple of 8.
This is because padding is required to make it unambiguous as the data is read in long chunks.

There might be some tricks to make this better such as stripping padding and knowing length but than you loose sort order.

Luckily most Ids are either 64 bit, 128 bit or 256 bit. For data that is multiple of 8 the algorithm will mostly be the same as shortuuid and base64 (11 characters per 8 bytes) provided the data isn't sparse (eg lots of zeros) which is usually not the case with random ids or even sufficiently large time ids.

For small monotonically increasing ids it would suck but you would probably use a number for that case anyway (e.g. old school database sequential ids).

**Comment by skorokithakis** [comment]
Ah, I see. The other issue is that many people rely on encoding/decoding being the same, and this will break backwards compatibility for tons of users.

As far as I know, you don't lose sorting:


```
In [24]: s.decode("3")
Out[24]: UUID('00000000-0000-0000-0000-000000000001')

In [25]: s.decode("4")
Out[25]: UUID('00000000-0000-0000-0000-000000000002')

In [26]: s.decode("3333334")
Out[26]: UUID('00000000-0000-0000-0000-000820bb4b60')
```

Is this not correct?

**Comment by agentgt** [comment]
I definitely do not think you should change shortuuid (this library) format as people have already used / stored it.

As for the sorting example. Decoding takes strings and not numbers. 
`3333334` should be before `4`.

```
>>> list = ['3','4','3333334']
>>> list.sort()
>>> print list
['3', '3333334', '4']
```

```
>>> uuids = [UUID('00000000-0000-0000-0000-000000000001'), UUID('00000000-0000-0000-0000-000000000002'), UUID('00000000-0000-0000-0000-000820bb4b60')]
>>> uuids.sort()
>>> uuids
[UUID('00000000-0000-0000-0000-000000000001'), UUID('00000000-0000-0000-0000-000000000002'), UUID('00000000-0000-0000-0000-000820bb4b60')]
```

**Comment by agentgt** [comment]
Part of the problem is you are fundamentally packing the data like its a giant number and not bytes.  Consequently shortuuid requires all the bytes be read before it starts encoding. I don't know if strings are a special case in shortuuid but the most significant bytes (MSB) should be packed first (left to right). 

This is how UUIDs are constructed in most systems:

```java
    private UUID(byte[] data) {
        long msb = 0;
        long lsb = 0;
        assert data.length == 16 : "data must be 16 bytes in length";
        for (int i=0; i<8; i++)
            msb = (msb << 8) | (data[i] & 0xff);
        for (int i=8; i<16; i++)
            lsb = (lsb << 8) | (data[i] & 0xff);
        this.mostSigBits = msb;
        this.leastSigBits = lsb;
    }
```

(its notable that the remainder bytes are ignored).

This is why padding is important for small numbers for our algorithm (for the remainder you can assume '2' and '0' are synonymous as '0' is padding but will more or less equate to 2 since we are dealing with 128 bits). 


'3' could be interpreted  (as loading it into MSB first).

`00000000-0000-0001-0000-000000000000` aka `0000000000300000000000`


Or it could be (loading it into LSB)

`00000000-0000-0000-0000-000000000001` aka `0000000000000000000003` aka `2222222222222222222223`

Or it could be:

`3222222222222222222222` which leads to some weird looking UUID in both algorithms but in ours the LSB would be zeroed out.


The first one follows how arbitrary byte encoding should work. It's also how the hex string description of  UUID works in general as the hex is left to right with MSB first. So the UUID strings themselves preserve sort order as well as if you were to encode it with [Base 32 hex](https://datatracker.ietf.org/doc/html/rfc4648#section-7) ( however not base64... I will never understand why Base64 alphabet is not in order).

**Comment by agentgt** [comment]
fssuid = my algorithm

The below UUIDs are in correct sort order.

| UUID | shortuuid | fssuuid |
|------|-----------|--------|
|`00000000-0000-0000-0000-000000000001`|322222222222222222222|2222222222222222222223|
|`00000000-0000-0000-0000-000000000002`|422222222222222222222|2222222222222222222224|
|`00193e28-6af4-12c7-2ec0-7d713c9cc3e2`|322222222222222222223|238mafpfpYsBKQwJKPPwmk|
|`05063365-9656-d971-0000-000000000000`| 2222222222yDNELiVqLxt |3222222222222222222222

**Comment by skorokithakis** [comment]
Hmm, which shortuuid are you using?:

```
In [1]: shortuuid.encode(uuid.UUID("00000000-0000-0000-0000-000000000001"))
Out[1]: '2222222222222222222223'
```

**Comment by agentgt** [comment]
Ahh it appears the Java and Golang version are doing the wrong thing. The Java one especially so.

I was going to test the python version against it next.

**Comment by agentgt** [comment]
Yeah it appears to be some kind of padding issue where the Java version is stripping the leading 2s.

It does appear though if shortuuid does the decoding it will generate stable sortable ids! My apologies on not using the python version.

**Comment by agentgt** [comment]
Yeah here is the issue:

https://github.com/hsingh/java-shortuuid/blob/2a4d72f195a3900ef86492173a51f6cad9f25969/src/main/java/com/hsingh/shortuuid/ShortUuid.java#L64

```java
    Double factor = Math.log(25d) / Math.log(alphabetSize);
```

It should be `256d` and not `25d`.

That being said at least on Java my algorithm still runs faster than say [bitcoinj base58](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/Base58.java) by a couple of factors however with a slight increase in length.

Sorry for wasting your time but it was helpful to me. I should have not trusted the Java one but it was easiest for me to test against.

**Comment by skorokithakis** [comment]
Yes, those are completely separate projects that just happen to be named similarly.

**Comment by agentgt** [comment]
It's not just that. You changed the format. It appears the Java version was using the old format... its my fault as I just didn't scroll to the bottom.
