### ISSUE TITLE
Django Model Field max_length does not account for length of prefix

### ISSUE THREAD

**Issue by jensenbox** [skorokithakis/shortuuid#71]
If you craft a new model field and specify a prefix but do not include the lenght, the max_length of the field is too short to contain the resultant uuid.

https://github.com/skorokithakis/shortuuid/blob/master/shortuuid/django_fields.py#L16 needs to add the length of the prefix if one is supplied.

**Comment by skorokithakis** [comment]
Oh oops, good catch, thank you. I'll fix that now.

**Comment by skorokithakis** [comment]
I've pushed a fix, @jensenbox! Could you make sure that that fixes your issue? Thanks!
