### ISSUE TITLE
DataError: invalid input syntax for type uuid

### ISSUE THREAD

**Issue by michaelbrant** [skorokithakis/shortuuid#73]
Django Version: | 4.0.1
Exception Type: DataError
Exception Value: invalid input syntax for type uuid: "HxXrBSybVoBjkXif" LINE 1: ...ES ('820008d1-b486-480b-92ec-accf5e722ef8'::uuid, 'HxXrBSybV...

So I had a Django model field that was a UUIDField and I want to migrate it to a ShortUUIDField like this:
# Before
```
    id = models.UUIDField(
         primary_key=True, default=uuid.uuid4, editable=False)
```
# After
```
    id = ShortUUIDField(
        length=16,
        max_length=40,
        primary_key=True,
    )
```

The makemigrations and migrate commands ran just fine. But when I try to create an instance of the object I get the above error in the Django admin console. 
I haven't found anything on stackoverflow about this. Am I missing a step? 
Also, sorry if this is not the right place for this question.

**Comment by michaelbrant** [comment]
This appears to be a Django migrations issue. I'm using a foreign key for the model and the Django migration did not update the database to expect a character field instead of a uuid field. Not sure how to fix this.. 
I thought Django migrations would be smart enought to update...

**Comment by johnvonneumann7** [comment]
Any progress?

**Comment by skorokithakis** [comment]
Hmm, do we need to add the migrations on our side? That seems unlikely, given how we don't have models, but I'm not sure what causes the error.
