### ISSUE TITLE
Please include type hints

### ISSUE THREAD

**Issue by adamcircle** [skorokithakis/shortuuid#75]
I'm happy to help write the type hints but I'm not sure how it would work with Python versions 3.0-3.4.

**Comment by skorokithakis** [comment]
I don't think we need to worry about those, they're very old. 3.5+ is fine, if you can.

**Comment by liminspace** [comment]
Add also supporting python versions up to 3.10

**Comment by anilsg** [comment]
FYI `mypy` appears to provide a tool for automatically generating a draft set of type hints:

> These stub files do not need to be complete! A good strategy is to use stubgen, a program that comes bundled with mypy, to generate a first rough draft of the stubs. You can then iterate on just the parts of the library you need.

- https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

**Comment by skorokithakis** [comment]
This should now be done.
