### ISSUE TITLE
Request to update format of license in pyproject.toml

### ISSUE THREAD

**Issue by markpaynter** [skorokithakis/shortuuid#78]
Hello!

I want to start by saying thank you for such a great python module and for making it available for everyone to use.

Looking at the license  of this module on pypi.org it does not seem to match the actual license included in here:
https://github.com/skorokithakis/shortuuid/blob/master/COPYING

Could you please update this file:
https://github.com/skorokithakis/shortuuid/blob/master/pyproject.toml#L5

to accurately reflect the license?

I believe the line needs to be the following:
`license = License :: OSI Approved :: BSD License`

It would be greatly appreciated as it seems the current state of things reflects your desired license incorrectly and this can prevent it from being scanned successfully by some auditing tools out there.

If you would prefer me to create a PR for this, I would be happy to oblige.

Thanks!

**Comment by markpaynter** [comment]
PR created. Thanks for the speedy response!

**Comment by skorokithakis** [comment]
Merged, thank you!

**Comment by ecederstrand** [comment]
Late to the game here, but this change is incorrect.

The `license` entry should not be in the delimited "classifiers" form. That format is only for the `classifiers` entry. There's no official specification of this field, AFAIK, but the generally accepted standard is to use the SPDX identifier of the license, assuming the license is OSI-approved. In this case, the license is https://opensource.org/licenses/BSD-3-Clause and the `license` entry would be `BSD-3-Clause`. This helps license checkers like e.g. `piplicences` to correctly identify the license 
of a package.

**Comment by skorokithakis** [comment]
Thanks for the correction, @ecederstrand. I've merged your PR, thank you!

**Comment by ecederstrand** [comment]
You're welcome! And thanks for the fast response :-)
