### ISSUE TITLE
Add MSB-first to https://shortuuid.com/

### ISSUE THREAD

**Issue by MotasemAghbar** [skorokithakis/shortuuid#81]
I'm not sure how is the owner of https://shortuuid.com/, but I think this is the right place to post the request.

I'm heavly using shortuuid in the system, so I'm using https://shortuuid.com/ to convert UUID<->shortuuid. However, I'm using shortuuid v1.0.9 which has MSB-first decoding while the site use legacy decoding, so I'm using string reverse tool to get the MSB shortuuid.

It would be great if you can add a new field for MSB or a radio button to switch to MSB decoding to https://shortuuid.com/ 

Thanks!

**Comment by skorokithakis** [comment]
Unfortunately, I don't know who the owner is, they did contact me ages ago but I forgot the contact info and I can't find any on the site...

**Comment by mosquito** [comment]
@MotasemAghbar I am the author of the shortuuid.com site, and I will try to fix this, but I need advice from @korokithakis on how to support the legacy format on the modern version of the library, so that I don't have to do something complicated with installing several versions of the library at once.

**Comment by skorokithakis** [comment]
@mosquito the latest version already supports it, all you have to do is pass `legacy=True`.

Would you consider open-sourcing the site? By the way, it occurs to me that you can have the site be completely static by compiling ShortUUID for the browser with Transcrypt, if you want.

**Comment by mosquito** [comment]
@skorokithakis thanks, I don't keep track of library changes, so thanks anyway for the hint.

I was thinking of making an open-source project, it just takes effort and time, I'm sorry but not a right now.

**Comment by mosquito** [comment]
@MotasemAghbar now https://shortuuid.com has a checkbox `Use legacy shortuuid format`

@skorokithakis I also added an explanation about independence from this project
<img width="559" alt="image" src="https://user-images.githubusercontent.com/792981/181738120-d5d7665c-86ea-494d-bb9f-44df1f59837e.png">

**Comment by skorokithakis** [comment]
Thank you, that looks great!

**Comment by MotasemAghbar** [comment]
@mosquito Thank you for your response and the fix!

I just took a look to it and its working well when try to convert shortuuid to UUIS. However, there is an expectation when trying to convert UUID to shortuuid.

The root cause is that `encode` method doesn't accept `legacy` param, it's only supported in decoding. 

I think the fix is straight forward by eliminating `lagacy=True` when call `encode` method. 

I really appreciate your time and effort. Also, I'd be happy to contribute to your library and fix this if that works!


Thanks!

**Comment by mosquito** [comment]
And that's one of the reasons why it's not open source. There's a test of tests, and it was done in a hurry.

@MotasemAghbar now I will try to fix everything, please do not stop, and write if you find something else.

**Comment by mosquito** [comment]
@MotasemAghbar fixed

**Comment by mosquito** [comment]
@MotasemAghbar my bad now it's correct

**Comment by MotasemAghbar** [comment]
@mosquito Perfect, thank you!

**Comment by mosquito** [comment]
Ooops, site had been recovered. Sorry guys.
