### ISSUE TITLE
ShortUUIDField does not generate an actual UUID decodable string

### ISSUE THREAD

**Issue by joshua-jandyco** [skorokithakis/shortuuid#82]
**Expectation:**
I thought based on the name of the field, that it would generate a UUID decodable string.  The README states:
`shortuuid includes a Django field that generates random short UUIDs by default`

**Actual:**
Looking at the `Field.__init__()`: it sets Field.default to be `ShortUUIDField._generate_uuid()`
```python
def __init__(self, *args, **kwargs):
    ...
    self.alphabet = kwargs.pop("alphabet", None)
    kwargs["default"] = self._generate_uuid
    ...
   
def _generate_uuid(self):
    """Generate a short random string."""
    return self.prefix + ShortUUID(alphabet=self.alphabet).random(
        length=self.length
    )
```
And generate calls ShortUUID.random which uses os.urandom and not the `uuid` module.
```python
def random(self, length=None):
    """Generate and return a cryptographically secure short random string of `length`."""
    if length is None:
        length = self._length

    random_num = int(binascii.b2a_hex(os.urandom(length)), 16)
    return int_to_string(random_num, self._alphabet, padding=length)[:length]
```

Maybe I'm missing something here, but it doesn't seem that this field generates an i**dentifier that is universally unique.** Wouldn't this be antithetical to the name of the field?

**Comment by skorokithakis** [comment]
You're right, it should generate UUIDs. However, then the `length` argument would need to be removed, as you can't specify the length of UUIDs.

If you'd like to submit a PR to return a valid UUID when the `length` argument isn't passed, I'd merge it.

**Comment by skorokithakis** [comment]
I think this was resolved in the PR.
