### ISSUE TITLE
CI is not running on master

### ISSUE THREAD

**Issue by pavelzw** [skorokithakis/shortuuid#86]
In the `pre-commit.yml` and `test.yml`, it is specified that the CI only works when pushed on `main`, see [here](https://github.com/skorokithakis/shortuuid/blob/c4a0a0edfdb1a876df17470af4117bf919208391/.github/workflows/pre-commit.yml#L6) and [here](https://github.com/skorokithakis/shortuuid/blob/c4a0a0edfdb1a876df17470af4117bf919208391/.github/workflows/test.yml#L6). This repository's default branch is `master`, though. You can fix this behavior by either renaming `master` to `main` or by replacing `main` with `master` in the CI yml files.

**Comment by skorokithakis** [comment]
Oops, thank you! Would it be possible to file a PR to fix the config? I'm currently away from the computer.

**Comment by pavelzw** [comment]
Sure 👍🏻
