### ISSUE TITLE
Please release new version to PyPi

### ISSUE THREAD

**Issue by polastre** [skorokithakis/shortuuid#88]
Please release a new version with the typing hints that were merged. Thank you!

**Comment by skorokithakis** [comment]
Released 1.0.10, thanks!

**Comment by polastre** [comment]
Thanks! Looks like you are missing a `py.typed` file. PR coming to you to include one, then would appreciate another minor release to include that.

See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker for more info

**Comment by polastre** [comment]
@skorokithakis would you mind releasing `1.0.11` with this change?

**Comment by skorokithakis** [comment]
I will, I'll wait a bit first for things to settle, as we already had #90 and I'd have to release another version with it :P

**Comment by skorokithakis** [comment]
Released!

**Comment by polastre** [comment]
Awesome thanks!
