### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by konstantinjdobler** [skorokithakis/shortuuid#91]
Since `1.0.11` I am getting the following error:  
```python
File "<path/to/env>/lib/python3.10/site-packages/shortuuid/__init__.py", line 1, in <module>
    from shortuuid.main import decode
ValueError: source code string cannot contain null bytes
```
I tested with `1.0.10` and `1.0.8` and the error does not occur before `1.0.11`.

**Comment by skorokithakis** [comment]
Hm, I can't reproduce this. Can you debug to see where the null bytes are?

**Comment by konstantinjdobler** [comment]
Okay, so my `shortuuid/main.py` consists of ONLY null bytes `\x00`:
```
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
```

Some info: I am using `conda` and am on `linux-x86`. Using `pip` to install `shortuuid==1.0.11` works fine and I can confirm that the `main.py` is okay. So my guess was that the `conda` build got messed up for `1.0.11`.

However, when I manually check the files in the [latest conda build](https://anaconda.org/conda-forge/shortuuid/1.0.11/download/noarch/shortuuid-1.0.11-pyhd8ed1ab_0.tar.bz2), `main.py` seems to be fine...

Therefore, I don't think the issue is on your end but rather something specific to my system. My easy fix for now is to just use `pip`.
