### ISSUE TITLE
Does not recognize shortuuid cli

### ISSUE THREAD

**Issue by bziraoui** [skorokithakis/shortuuid#93]
Hello, 

When i try to use commande-line shortuuid does not recognize.

```shell
$ pip install shortuuid
Collecting shortuuid
Installing collected packages: shortuuid
Successfully installed shortuuid-0.5.0

$ shortuuid -h
shortuuid: command not found

```

What i am doing wrong ?

**Comment by skorokithakis** [comment]
Hmm, it looks like you haven't added your `bin` directory to your PATH, I'm not sure how you can do that in your current system, though. You'd have to consult that documentation.
