### ISSUE TITLE
deadbeefcafe shortuuid equivalent?

### ISSUE THREAD

**Issue by gitpushdashf** [skorokithakis/shortuuid#96]
Hi!

This is really cool!

One unusual question, though. For shortuuid, do you have any kind of `deadbeefcafe` equivalent? Something for example IDs and documentation purposes?

Given the base57 alphabet, this is what I've come up with so far: `ShrtUUEyeDg4EYpKwxL8Xc`

I'm sure there's a better way to do it. It doesn't even seem all that obvious to have a special prefix. I guess DeadBeefCafe would also be valid. In that case, it could look like: `DeadBeefCafeZXP3g4Rjoe`

Thanks!

**Comment by skorokithakis** [comment]
Hello!  
Hmm, I'm not sure what you mean. What's `deadbeefcafe`?

**Comment by gitpushdashf** [comment]
`deadbeefcafe` is a hex phrase you can use to help find something obscure in a hex editor. Like if you set something to that value, you know it's set by a human.

Here's some more information on it: https://en.wikipedia.org/wiki/Magic_number_(programming)

Just a way to have a human generated example that you know is an example and not a special thing, but is obviously a shortuuid (ideally).

**Comment by skorokithakis** [comment]
Oh, right. In that case, anything would work, since the alphabet supports almost every letter. Eg `HereWeHaveAShortUuid`.

**Comment by gitpushdashf** [comment]
That looks really good! But isn't `o` omitted? Or is it just uppercase `O` and `0`?

**Comment by skorokithakis** [comment]
Yep, just uppercase.

**Comment by gitpushdashf** [comment]
Very helpful, thank you! I appreciate it!
