### ISSUE TITLE
Changing alphabet change shortuuid length to 25

### ISSUE THREAD

**Issue by KinanLak** [skorokithakis/shortuuid#98]
Hello,

When I'm trying to generate an uuid this happens :

Step to reproduce (Python 3.11.2 Shortuuid 1.0.11) :
```
>>> import shortuuid
>>> shortuuid.get_alphabet()
'23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
>>> shortuuid.uuid()
'iaFttNEzNGCcwUfYsKhvjr'
>>> shortuuid.set_alphabet('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ')
>>> shortuuid.uuid()
'2STM4XVS7Y6MMJX1VJIOWN1ZK'
```
'iaFttNEzNGCcwUfYsKhvjr' has a len of 22
But
'2STM4XVS7Y6MMJX1VJIOWN1ZK' has a len of 25

I don't really know why this occurs

**Comment by skorokithakis** [comment]
Shorter alphabets produce longer strings, since you need to fit a fixed number of bits in them.
